<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-DIP3NAVD" name="com.target.qa.testcases.TopDealsPageTest" tests="3" failures="2" timestamp="12 Feb 2022 17:58:33 GMT" time="103.548" errors="0">
  <testcase name="verifyTopDealsPageDisplayed" time="19.226" classname="com.target.qa.testcases.TopDealsPageTest"/>
  <testcase name="verifyDealsOnEveryDayEssentialsSectionDisplayed" time="43.362" classname="com.target.qa.testcases.TopDealsPageTest">
    <failure type="java.lang.AssertionError" message="Deals On Every Day Essentials Section Not Displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Deals On Every Day Essentials Section Not Displayed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.target.qa.testcases.TopDealsPageTest.verifyDealsOnEveryDayEssentialsSectionDisplayed(TopDealsPageTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verifyDealsOnEveryDayEssentialsSectionDisplayed -->
  <testcase name="verifySavingWaysCount" time="40.960" classname="com.target.qa.testcases.TopDealsPageTest">
    <failure type="java.lang.AssertionError" message="Saving Ways Count is incorrect expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Saving Ways Count is incorrect expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.target.qa.testcases.TopDealsPageTest.verifySavingWaysCount(TopDealsPageTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verifySavingWaysCount -->
</testsuite> <!-- com.target.qa.testcases.TopDealsPageTest -->
